### ISSUE TITLE
Play button appears in top left corner

### ISSUE THREAD

**Issue by dvoigt** [lochmueller/html5videoplayer#11]
Hi, in the frontend plugin of the latest (6.7.0) version of the extension the play button sticks to the top left corner of the player (with a bit of margin), instead of being centered. 

Tested in browsers: Firefox 45.3.0, Chromium 52.0.2743.
Firebug tells me

`.vjs-default-skin .vjs-big-play-button {
    (...)
    position: absolute;
    left: 0.5em;
    top: 0.5em;
    vertical-align: middle;
}`

**Comment by dvoigt** [comment]
Apparently, this is the intended behavior in video-js and can be changed there. So I guess this can be closed, unless you want to change it into a feature request: Include option to remove the CSS the extension includes from CDN or use your own CSS file (which can be created at [codepen](http://codepen.io/heff/pen/EarCt)).

**Comment by lochmueller** [comment]
I close this issue... there will be a update soon. Perhaps I add the "Move play to center-center"-function in the next big release...
