### ISSUE TITLE
Template is not responsive

### ISSUE THREAD

**Issue by dvoigt** [lochmueller/html5videoplayer#12]
Editors can set a static width and height for the player, but there's no easy way to make the player work well with RWD. There is a [guide](https://coolestguidesontheplanet.com/videodrome/videojs/) how to do it. It would be cool to have a switch for the container class (vjs-16-9 or vjs-4-3), have max-width set to 100% and width (used as min-width) be set by the editor. That way more people could use the extension out-of-the-box.

**Comment by saitho** [comment]
HTML5Videoplayer uses an old version of Video.js, the latest version supports responsiveness (also the video controller was changed a bit).

**Comment by lochmueller** [comment]
Git master and next release was updated to current VideoJS version. Please recreate a new issue if there are still problems with responsive HTML output
