### ISSUE TITLE
problem by adding new record of video in TYPO3 BE

### ISSUE THREAD

**Issue by p380** [lochmueller/html5videoplayer#17]
when i want  to add new record of video in plugin, the label of title is not OK, includes many commas separating of fields... How to adjust to initially display the label "no title", then title of video?

**Comment by lochmueller** [comment]
Ufff... I think this handle TYPO3 (perhaps a strange MM record handling). Please report your TYPO3 Version and Extension Version so I can check this...

**Comment by p380** [comment]
TYPO3 version is 6.2.26
Extension version is  6.7.3

**Comment by p380** [comment]
Did you find the solution?

**Comment by lochmueller** [comment]
Hey @p380 It is only three days ago ;) I will check this in the next weeks... Many tasks on my todo list at the moment... sorry.

**Comment by lochmueller** [comment]
We will drop the 6.x suppoert for the next release.... so the issue is closed: https://github.com/lochmueller/html5videoplayer/commit/09482a3c8e3e3b453153126abd498f774878cee0
