### ISSUE TITLE
Move JavaScript files from the header to the footer

### ISSUE THREAD

**Issue by pixelbreit** [lochmueller/html5videoplayer#19]
Hi, 
is it possible to move the JavaScript and CSS files from the header to the footer of the page?

**Comment by lochmueller** [comment]
No... at the moment the logic is part of the Controller: https://github.com/lochmueller/html5videoplayer/blob/master/Classes/Controller/VideoplayerController.php#L240 If you want to move the CSS/JS arround, the first step should be the migration of the JS/CSS resources to TypoScript...

**Comment by pixelbreit** [comment]
ok, is there a chance that you integrate this as a feature in the next version?

**Comment by lochmueller** [comment]
There is no next version planed at the moment. But keep this issue open... I will check this again at the beginning of 2017....

**Comment by lochmueller** [comment]
You can disable the header of the internal function and load the needed files by yourself. I added a example to the current master: https://github.com/lochmueller/html5videoplayer/commit/317d4a295f35d1835024f1cb6e48b63319562c61
