### ISSUE TITLE
No compatible source was found for this media.

### ISSUE THREAD

**Issue by Nestrot** [lochmueller/html5videoplayer#20]
Hi Tim,

after updating from 6.7.3 to 7.0.0 i see the error "No compatible source what found for this media." A youtube video is used.
After downgrade from 7 to 6.7.3 everything works again.

Regards, Torsten

**Comment by lochmueller** [comment]
Hey @Nestrot 
Do you have some more information? Are the JS/CSS files of VideoJS and the Vimeo-/YouTube-Plugin loaded in the page?
Regards,
Tim

**Comment by Nestrot** [comment]
Hi Tim, i have downgrade to 6.7.3. If I have some time, I test the version 7 again and look.
Regards, Torsten

**Comment by lochmueller** [comment]
Fixed in current master...
