### ISSUE TITLE
Reponsive Einbindung 

### ISSUE THREAD

**Issue by quadronet** [lochmueller/html5videoplayer#21]
Leider funktioniert das einbinden nicht wie gewünscht: 

CSS Fehlermeldung:
#video_2 {padding-top: ERROR: dividing by zero%}

Egal was ich mache, die Berechnung klappt nicht, width und height im Video stehen auf auto.

lib.calc ist im Setup der Seite eingetragen, hier noch das Template:

<div class="video-js-box ">

                <style type="text/css">
                #video_{video.uid}  {padding-top: <f:cObject typoscriptObjectPath='lib.math' data='({settings.ff.videoheight})/{settings.ff.videowidth}*100'/>%}
                .vjs-fullscreen {padding-top: 0px}
                </style>

                <video id="video_{video.uid}" class="video-js vjs-default-skin" width="{f:if(condition:'{settings.ff.videowidth} > 0', then: settings.ff.videowidth, else: video.minWidth)}" height="{f:if(condition:'{settings.ff.videoheight} > 0', then: settings.ff.videoheight, else: video.minHeight)}" preload="{video.preloadvideo}"<f:if condition="{video.autoplayvideo}"> autoplay</f:if><f:if condition="{video.loopvideo}"> loop</f:if><f:if condition="{video.posterimage}"> poster="{video.posterimage}"</f:if><f:if condition="{video.controlsvideo}"> controls</f:if> data-setup='{<f:if condition="{video.videoStarttime}">"starttime": {video.videoStarttime},</f:if><![CDATA["techOrder":["youtube","vimeo","html5","flash"], "ytcontrols": true]]>}'>
                               <f:if condition="{video.webmsource}"><source src="{video.webmsource}" type="video/webm" /></f:if>
                               <f:if condition="{video.oggsource}"><source src="{video.oggsource}" type="video/ogg" /></f:if>
                               <f:if condition="{video.mp4source}"><source src="{video.mp4source}" type="video/mp4" /></f:if>
                               <f:if condition="{video.youtube}"><source src="{video.youtube}" type="video/youtube" /></f:if>
        <f:if condition="{video.vimeo}"><source src="{video.vimeo}" type="video/vimeo" /></f:if>
                </video>
                <p class="vjs-no-video">
                               <f:if condition="{video.downloadlinks}">
                                               <strong>Download "{video.title}"-Video:</strong>
                                               <f:if condition="{video.mp4source}"><a href="{video.mp4source}">MP4</a> </f:if>
                                               <f:if condition="{video.webmsource}"><a href="{video.webmsource}">WebM</a> </f:if>
                                               <f:if condition="{video.oggsource}"><a href="{video.oggsource}">Ogg</a></f:if>
                                               <f:if condition="{video.youtube}"><a href="{video.youtube}">YouTube</a></f:if>
            <f:if condition="{video.vimeo}"><a href="{video.vimeo}">Vimeo</a></f:if>
            <br />
                               </f:if>
                               <f:if condition="{video.supportvideojs}">
                                               <a href="http://videojs.com/">HTML5 Video Player</a> by VideoJS
                               </f:if>
                </p>
                <f:if condition="{video.description}">
                               <f:format.html>{video.description}</f:format.html>
                </f:if>
</div>

**Comment by lochmueller** [comment]
Siehe die Rechnung: ({settings.ff.videoheight})/{settings.ff.videowidth}*100
"auto" wird natürlich als "0" erkannt. Die Responsiven Einstellungen mit dem lab.math gehen nur (!!!), wenn du auch echte Dimensionen im Flexform angibst. Dann wird entsprechend das passing-top entsprechend der Video Dimension gesetzt, damit die Dimension immer geht. Die Breite setzt du dann über dein eigenes CSS.

Ticket schließe ich ab.

**Comment by lochmueller** [comment]
PS: Issues bitte in Englisch anlegen, sodass jeder der die Infos hier findest helfen kann und nicht nur die deutschsprachige Community....
