### ISSUE TITLE
Fix for TYPO3 8

### ISSUE THREAD

**Issue by SicorDev** [lochmueller/html5videoplayer#22]
Hello,

the array "enabledControls" from html5videoplayer/Configuration/TCA/Overrides/tt_content.php breaks the TCA for TYPO3 8 I think. You should either set all values to "=> true" or just remove the entire array, as the values already seem to be all true by default.

Greetings,
Manuel

**Comment by lochmueller** [comment]
Thanks. Will be part of the next release...
