### ISSUE TITLE
No compatible source was found for this media. TYPO3 8.7

### ISSUE THREAD

**Issue by deividasgab** [lochmueller/html5videoplayer#23]
Hi,

I've installed html5videoplayer 7.0.1 to TYPO3 8.7.4 and tried to put some youtube, vimeo, local videos, but I couldn't, I got the error below:

![html5videoplayer_bug](https://user-images.githubusercontent.com/31312446/29666716-26716de2-88e2-11e7-8f41-82848617e1e9.PNG)

NOTE:  same version of html5videoplayer works perfect in TYPO3 7.6 version.

**Comment by lochmueller** [comment]
Fixed in current master (incl. update of VideoJS). Only Vimeo have some problems...

**Comment by K00764** [comment]
Hello, having problems using extension with vimeo here too. It shows video timeline and control button, but no video. The error message is "No video with supported format and MIME type found." ? Maybe some problems with headers?

**Comment by lochmueller** [comment]
Do you use the current master version? https://github.com/lochmueller/html5videoplayer/releases/tag/7.1.0

**Comment by K00764** [comment]
yes

**Comment by lochmueller** [comment]
@K00764 I need some more information of your problem. Debugging infos. Do you have a test page online so I can check the frontend?

**Comment by lochmueller** [comment]
Problems are solved in the current master. There was missing JS files and wrong JS URIs
