### ISSUE TITLE
Error: Hash does not validate

### ISSUE THREAD

**Issue by Lemmork** [lochmueller/html5videoplayer#24]
If I click on the "Create new" or "Create new relation" button to add a video to the frontend-plugin. I get an "Error 500".
Taking a deeper look into the logs it says:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1489751363: Hash does not validate | RuntimeException thrown in file /var/www/html/Packages/Libraries/typo3/cms/typo3/sysext/backend/Classes/Controller/FormInlineAjaxController.php in line 750. Requested URL: https://mydomain.tld/typo3/index.php?ajaxID=%2Fajax%2Frecord%2Finline%2Fcreate&ajaxToken=16774644a68b27a573606667569cb0da2a6ec35f

Any hints on this?

TYPO3: 8.7.4
html4videoplayer: 7.0.1

**Comment by lochmueller** [comment]
Hmmm... looks strange. I don't know... do you have some deeper debug information?

**Comment by Lemmork** [comment]
Unfortunately not.
I tried to debug the hash-calculation, but did not find strange things.
You can reproduce it with the typo3 docker image (https://github.com/martin-helmich/docker-typo3).

Works fine with 7.6.

**Comment by Lemmork** [comment]
I created a pull request for this issue. Apparently the values in enableControls have to be set in TYPO3 8.

**Comment by lochmueller** [comment]
Thanks.... added to the current master!
