### ISSUE TITLE
TYPO3 8.7 - bug DB check -> Records Statistics

### ISSUE THREAD

**Issue by p380** [lochmueller/html5videoplayer#25]
hy,

when I using TYPO3 module "DB check -> records statistics", it displays an error
	
Oops, an error occurred!
An exception occurred while executing 'SELECT `uid`, `pid`, `Video/Content Relation` FROM `tx_html5videoplayer_video_content` WHERE `pid` NOT IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [0, 1328, 1367, 12236, 1353, 12447, 12448, 12449, 12450, 12751, 12789, 12746, 12752, 1333, 1366, 12454, 12455, 12747, 12459, 1375, 12553, 12552, 12551, 12550, 12548, 12561, 12562, 12748, 12749, 12750, 12754, 12755, 12756, 12757, 12760, 12758, 12759, 12762, 12766, 12768, 12783, 1342, 1331, 12216, 12223, 12219, 12218, 12743, 12744, 12745, 12217, 1347, 1349, 12214, 12215, 1348, 1329, 12279, 1338, 1339, 1337, 6073, 12792, 12024, 12034, 12033, 12032, 12031, 12030, 1332, 1336, 1335, 1334, 12025, 11996, 12027, 12026, 1330, 11944, 12142, 12143, 12144, 12564, 12761, 12790, 12791, 1341, 12145, 565]: Unknown column 'Video/Content Relation' in 'field list'

kind regards

**Comment by SicorDev** [comment]
Fix:
Since the table 'tx_html5videoplayer_video_content' has no label column, remove this line from typo3conf/ext/html5videoplayer/Configuration/TCA/tx_html5videoplayer_video_content.php :
'label'     => 'Video/Content Relation',
