### ISSUE TITLE
Outdated version on TYPO3 TER?

### ISSUE THREAD

**Issue by nostadt** [lochmueller/html5videoplayer#26]
The TER contains the version of 3rd Jan 2017 https://extensions.typo3.org/extension/html5videoplayer/

However, the latest available version in this repository is from 21 days ago. Is there a particulary reason you did not upload it or did you simply forgot it?

Best regards
AMartinNo1

**Comment by lochmueller** [comment]
Hey @AMartinNo1 . I know.... some problems with the build process. It is recommended to use composer anyway.... but i will check this in the next days.

**Comment by lochmueller** [comment]
Already up to date....
