### ISSUE TITLE
Wrong JS sources in 7.2.2

### ISSUE THREAD

**Issue by giuseppe-cavallaro-ba** [lochmueller/html5videoplayer#28]
The current Version 7.2.2 has wrong JS paths.

For Example video.js

It tries to get the js file from this path: 
`typo3conf/ext/html5videoplayer/Resources/Public/video-js-6.2.7/video.js`

But the correct path is: 
`typo3conf/ext/html5videoplayer/Resources/Public/video.js-6.2.7/src/js/video.js`

Same for youtube-js file.

**Comment by lochmueller** [comment]
Fixd in current master. It is recommended to use the CDN.
