### ISSUE TITLE
wrong path to minified css files +Unexpected token import

### ISSUE THREAD

**Issue by giuseppe-cavallaro-ba** [lochmueller/html5videoplayer#29]
You fixed the path to the js files, but forgot the css file.
`html5videoplayer/Resources/Public/video.js-6.2.7/video-js.min.css`

Also I'm getting a Unexpected token import Error on the first import line of the video.js file.
`import {version} from '../../package.json';`

Any Ideas for this?

**Comment by lochmueller** [comment]
Please switch to CDN. I will drop the VideoJS files in the next version. It is much easier in the development workflow of the extension...

**Comment by lochmueller** [comment]
Fixed in current master. There was a wrong package in the extension. Switch the package to distribution package, adapt paths and also update to 6.2.8
