### ISSUE TITLE
Support TYPO3 7.5

### ISSUE THREAD

**Issue by GuillaumeGBzh** [lochmueller/html5videoplayer#3]
Hello,

html5videoplayer is not supported in TYPO3 7.5.

I get this exception when I want to create a new record:
#1437750231: The way registering a wizard in TCA has changed in 6.2 and was removed in CMS 7. Please set module[name]=module_name instead of using script=path/to/script.php in your TCA. (More information)

InvalidArgumentException thrown in file
/var/www/typo3-7/typo3/sysext/backend/Classes/Form/Element/AbstractFormElement.php in line 163.

**Comment by lochmueller** [comment]
Already fixed in current master. I close this issue....
