### ISSUE TITLE
Problems with TYPO3 8.7 and mediace

### ISSUE THREAD

**Issue by maximaexchen** [lochmueller/html5videoplayer#30]
I installed mediace, which seems not to be  compatible with TYPO3 8.7.
But still getting the error
"You are running TYPO3 > CMS 7.2. Please install the mediace extension"

Some ideas?

**Comment by mueller-sebastian** [comment]
Hi. Hatten das Problem auch. Das Problem liegt an Sonderzeichen/Leerzeichen in deinem Videonamen/Pfad.
Der Pfad zur Datei wird bei der Verwendung von t3:// via Typolink gebaut. Dadurch werden Sonderzeichen/Leerzeichen urlcodiert.
Fix:
In der html5videoplayer/Classes/Domain/Model/Video.php
nach Zeile 495 folgendes einfügen:
`$media = urldecode($media);`
dann wird es wieder urldecoded.

-----
I'm sorry, bad habit:
we had the same problem. It comes from spaces or special characters in the video/Poster filename or path.
The filepath of video records created in typo3 8 (t3://file?uid=xxx) will be generated using typolink. Typolink returns its urls urlencoded. But this will not work (e.g. for checking if file exists).
Fix: in html5videoplayer/Classes/Domain/Model/Video.php add the following after line 495:
`$media = urldecode($media);`
so filepath will be urldecoded.
