### ISSUE TITLE
Youtube.min.js is missing

### ISSUE THREAD

**Issue by ghost** [lochmueller/html5videoplayer#32]
File missing : 
EXT:html5videoplayer/Resources/Public/videojs-youtube-2.4.0/dist/Youtube.min.js

Youtube player not working in 7.2.2 version.

Face issue : 
TYPO3 8.7.4
html4videoplayer 7.2.2

-----
we only need to copy attached file into missing path : 
[Youtube.min.zip](https://github.com/lochmueller/html5videoplayer/files/1735943/Youtube.min.zip)

**Comment by lochmueller** [comment]
Already fixed in current master. Will be released soon....
