### ISSUE TITLE
Wrong label in TCA

### ISSUE THREAD

**Issue by ghost** [lochmueller/html5videoplayer#34]
Description :
In the file tx_html5videoplayer_video_content.php, the ctrl label is 'Video/Content Relation'
This label is a sql fields that corresponding to the label in list view.
See https://docs.typo3.org/typo3cms/TCAReference/Ctrl/Index.html for reference

Issue :
In Typo3 8.7.19 with html5videoplayer extention installed,
Loggued in the backend as admin,
When we try to use the "DB Check" we see an issue

`An exception occurred while executing 'SELECT uid, pid, Video/Content Relation FROM tx_html5videoplayer_video_content WHERE pid NOT IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [0, 1, 2, 3, 66, 68, 67, 111, 4, 20, 21, 22, 240, 249, 25, 244, 198, 242, 24, 228, 246, 230, 248, 23, 232, 15, 16, 17, 19, 59, 60, 61, 62, 63, 64, 65, 70, 71, 5, 73, 74, 374, 113, 117, 118, 119, 120, 121, 122, 123, 253, 183, 480, 268, 401, 77, 115, 116, 262, 502, 504, 72, 76, 6, 31, 263, 32, 33, 264, 266, 375, 34, 35, 8, 80, 83, 133, 146, 473, 475, 147, 148, 149, 150, 151, 152, 153, 157, 158, 159, 160, 161, 162, 179, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 156, 238, 93, 95, 202, 376, 206, 236, 154, 155, 188, 189, 226, 85, 87, 89, 9, 26, 251, 260, 255, 130, 129, 128, 127, 126, 125, 124, 257, 259, 497, 28, 29, 97, 27, 30, 261, 11, 78, 79, 82, 81, 199, 200, 201, 84, 86, 88, 112, 69, 92, 436, 434, 381, 383, 399, 400, 430, 431, 432, 433, 438, 439, 448, 449, 462, 463, 416, 472, 414, 444, 450, 464, 465, 417, 458, 460, 477, 412, 413, 410, 411, 382, 384, 379, 380, 377, 378, 223, 221, 91, 428, 429, 419, 456, 457, 454, 455, 452, 453, 446, 447, 442, 443, 440, 441, 426, 427, 424, 425, 422, 423, 420, 421, 94, 395, 478, 470, 481, 484, 397, 398, 486, 488, 489, 490, 491, 492, 493, 487, 503, 114, 270, 271, 98, 272, 370, 371, 346, 347, 344, 345, 342, 343, 340, 341, 338, 339, 336, 337, 334, 335, 332, 333, 330, 331, 348, 349, 350, 351, 368, 369, 366, 367, 364, 365, 362, 363, 360, 361, 358, 359, 356, 357, 354, 355, 352, 353, 328, 329, 326, 327, 324, 325, 292, 293, 290, 291, 288, 289, 286, 287, 284, 285, 282, 283, 280, 281, 278, 279, 276, 277, 294, 295, 296, 297, 314, 316, 317, 318, 319, 320, 321, 322, 323, 315, 312, 313, 310, 311, 308, 309, 306, 307, 304, 305, 302, 303, 300, 301, 298, 299, 274, 275, 273, 372, 373, 466, 467, 468, 469, 495, 494, 496, 187, 99, 100, 180, 181, 135, 141, 101, 102, 136, 137, 139, 138, 140, 186, 105, 132, 106, 185, 107, 389, 390, 207, 250, 225, 216, 213, 214, 211, 212, 209, 204, 205, 196, 197, 192, 194, 195, 193, 190, 191, 131, 104, 217, 218, 103, 108, 109, 110, 75, 41, 40, 39, 38, 37, 90, 36, 96, 134, 143, 144, 145, 14, 182, 7, 10, 235, 142, 42, 43, 45, 46, 47, 49, 265, 483, 500, 44, 48, 12, 58, 52, 18, 13, 227, 184, 234, 57, 56, 53, 54, 55, 51, 50, 498, 499]: Unknown column 'Video/Content Relation' in 'field list' 
`
A screen capture is joined

![html5videoplayerbug](https://user-images.githubusercontent.com/31665846/44832611-8fbe8880-ac2b-11e8-83f7-1bbcedff8ad1.PNG)

**Comment by lochmueller** [comment]
I close this issue. There is already a bug report related to this problem: https://github.com/lochmueller/html5videoplayer/issues/25
