### ISSUE TITLE
Nocookie option

### ISSUE THREAD

**Issue by msollmann** [lochmueller/html5videoplayer#35]
Hi,

a nocookie option would be great: https://www.heise.de/ct/ausgabe/2016-1-YouTube-Videos-datenschutzkonform-einbetten-3046316.html

Best regards
Michael

**Comment by kkugelmann** [comment]
This could be achieved by bumping videojs-youtube up to a Version > 2.5.0.
In Version 2.5.0 of videojs-youtube a privacy option was introduced: https://github.com/videojs/videojs-youtube/pull/497

Also see: https://github.com/videojs/videojs-youtube/issues/499

Everything that needs to be done further would be to add an option to the backend to set that option when calling the videojs script.
