### ISSUE TITLE
Database fields width and height should be integer

### ISSUE THREAD

**Issue by DavidBruchmann** [lochmueller/html5videoplayer#37]
... as the fields are converted to int anyway in the model.

**Comment by lochmueller** [comment]
I close this issue. The width and height are "strings" in the DB (and TCA), because there are also values like "auto" possible. Only the default values are vonverted to int. If you use "auto" you will get "auto" in your template.

Regards,
Tim

**Comment by DavidBruchmann** [comment]
Sounds reasonable, you could consider adding a negative integer for auto or restrict the length of the fields more.

**Comment by lochmueller** [comment]
Hmm... there are also values like "90%" allowed.

Note: I suggest to use the core functions to create Videos. There will be no release in the feature and only bugfixes via Github.

**Comment by DavidBruchmann** [comment]
You convinced me ;-)
Thanks for the additional info!
