### ISSUE TITLE
https for request to Vimeo

### ISSUE THREAD

**Issue by DavidBruchmann** [lochmueller/html5videoplayer#38]
In `VimeoProcessDatamap::processDatamap_postProcessFieldArray` is still a request  with http.
Should be changed to https.

`http://vimeo.com/api/v2/video/` => `https://vimeo.com/api/v2/video/`

**Comment by lochmueller** [comment]
Fixed in current master 👍

**Comment by DavidBruchmann** [comment]
Great :)
