### ISSUE TITLE
Missing js/css assets

### ISSUE THREAD

**Issue by w010** [lochmueller/html5videoplayer#39]
7.2.2 is not working out of the box, there's no assets in Resources, but it tries to include them. The missing files are:
- /Public/video-js-6.2.7/video-js.min.css
- /Public/video-js-6.2.7/video.js
- /Public/videojs-youtube-2.4.0/dist/Youtube.min.js
only videojs-vimeo.min.js is there.

(Maybe it's to be compiled by yourself, but no informations about that situation can be found in readme nor in documentation)

And when trying to build ie. youtube js I'm getting:
npm run build
> videojs-youtube@2.4.0 build 
Resources/Public/videojs-youtube-2.4.0
> mkdirp dist && cp src/Youtube.js dist/Youtube.js && uglifyjs src/Youtube.js -o dist/Youtube.min.js
'mkdirp' is not recognized as an internal or external command,
operable program or batch file.

**Comment by lochmueller** [comment]
The problem is already fixed: https://github.com/lochmueller/html5videoplayer/commit/72cc9577d9af2ecf5ad81f13bb8e27c5c17f789e I will create a release shortly.

**Comment by lochmueller** [comment]
Please upgrade to: 7.2.3
