### ISSUE TITLE
html5videoplayer should support translations

### ISSUE THREAD

**Issue by ABaechle** [lochmueller/html5videoplayer#4]
Hello,

we are using the html5videoplayer extension in our TYPO3 envionment and are very happy. 

But is it possible to make the extension translatable?

It is possible to choose diffent video files in TYPO3 backend. For example the German translation should show a different video in frontend than the English translation. But in fontend there is always the video of the default language (English).
It's the same behavior with the configuration (video height/width) of the translations.

Perhaps there is already an option to show the translations in frontend?

Thanks,
Best regards,
Andreas

**Comment by lochmueller** [comment]
Hey @ABaechle 
Thanks for the feedback. I will check this issue in the next days/weeks... There are no "options" in the extension for different language modes. I think it is a general problem and I have to check the different languages modes in combination with the extension.
Regards,
Tim

**Comment by lochmueller** [comment]
Fixed with https://github.com/lochmueller/html5videoplayer/pull/9
Thanks...

**Comment by bartlammers** [comment]
You're welcome
