### ISSUE TITLE
There is no videojs-youtube-2.6.0/dist directory at all

### ISSUE THREAD

**Issue by w010** [lochmueller/html5videoplayer#41]
There's no youtube tech compiled dist directory, expected in Resources/Public/videojs-youtube-2.6.0/dist/Youtube.min.js which causes error 404 and youtube videos not working in 7.2.2 nor 7.2.3
I'm pretty sure I stumbled on similar problem few months ago and this ext still doesn't work out of the box.

**Comment by lochmueller** [comment]
Hey @w010 
I will check this in the future. But please keep in mind, that the media URL integration of TYPO3 FAL is much smarter integration. So I don't know how many releases I will push to TER in the feauture.
Regards, Tim

**Comment by lochmueller** [comment]
The problem was the .gitignore of the videojs-youtube project. There was a ignore for `dist` so the folder was not added last time. Fixed 👍
