### ISSUE TITLE
Unable to create new video from plugin.

### ISSUE THREAD

**Issue by pfinkbeiner** [lochmueller/html5videoplayer#47]
`Create new` button acts like i've clicked `create new relation`. Instead of creating a new video it adds a relation of the first video shown in dropdown. Any idea? 

Happens on TYPO3 10.4.20 

![image](https://user-images.githubusercontent.com/722890/132478541-fb87e259-d5bc-40f7-b4fb-d5fca262bc9b.png)

**Comment by dennismetz** [comment]
I have created a bug report at TYPO3, it doesn't look like the error is coming from the extension itself.

https://forge.typo3.org/issues/97661

**Comment by lochmueller** [comment]
Ok. I will close this issue...
