### ISSUE TITLE
Issues with localization

### ISSUE THREAD

**Issue by dancodes** [lochmueller/html5videoplayer#48]
Hello,

We've ran into a problem regarding the translation of fields in your extension.

The TCA model `tx_html5videoplayer_domain_model_video` contains relevant `l10n_*` fields indicating that it is translatable. However, its child element `tx_html5videoplayer_video_content` lacks them, yet its parent table is of type `inline`.

This is troublesome for us as we assume that all translatable high-level content should also have translatable child elements.  We believe it's a reasonable design choice and would make your extension work out of the box with our translation module.

Would this be something you could consider updating?

**Comment by lochmueller** [comment]
Hey @dancodes 
The extension is not actively maintained anymore. Feel free to send pull-request and I will review, merge and release them. But currently I cannot actively support any features/issues for this extension. Sorry.
Regards,
Tim

**Comment by dancodes** [comment]
Hi @lochmueller

I will forward this to our team and we will decide what to do next.

I would like to thank you for your quick response and I fully understand the situation.

Have a nice day!

**Comment by lochmueller** [comment]
I will close this issue. Feel free to send PRs...
