### ISSUE TITLE
Support for TYPO3 12.4 

### ISSUE THREAD

**Issue by terminal8-nz** [lochmueller/html5videoplayer#53]
Are there any plans for a TYPO3 12 compatible version of this extension?
Thanks for your feedback! :)

**Comment by lochmueller** [comment]
Hey @terminal8-nz 
no, there is no timing or agenda for a new release for v12.
Also, there are much smarter solutions since TYPO3 v9 (Online media Helper, file collections etc.) that I suggest.
If there is support out of the community (code or financial) I could release a new version.
Regards,
Tim

**Comment by terminal8-nz** [comment]
Alright, thanks for your fast reply. I think we're gonna use another solution then 👍
Best regards, Nicole

**Comment by helipus** [comment]
What a pity. I really loved using this extension. Will look for something else then because I want to be able to update to TYPO3 v12. Thank a lot for the years with this great extension!
