### ISSUE TITLE
Vimeo videos won't play in Firefox

### ISSUE THREAD

**Issue by nurbs999** [lochmueller/html5videoplayer#8]
Hi there,

I' not sure if this is a bug in the extension but Firefox doen't play any vimeo videos if they get included via html5videoplayer. I testet it with TYPO3 7.6.9 and version 6.7 of the extension. All other browser just work fine. Firefox is complaining about unknown mimetype 'video/vimeo' and just stops loading.

Kind regards

**Comment by lochmueller** [comment]
Hey @nurbs999 
I cannot rebuild this problem. Do you have same more information? Perhaps a Link, that show the problem?
Regards,
Tim

**Comment by nurbs999** [comment]
Hi Tim,

I don't have a site that is accessible publicly but I did some further testing. This bug only affects Firefox under Mac OSX in combination with video.js. Your extension runs fine in Firefox under Windows and Linux. Maybe it's something the guys from video.js or Mozilla need to fix.

**Comment by lochmueller** [comment]
Hey @nurbs999 
at the moment the EXT:html5videoplayer use an old version of Video.js. I think we should update the version in the next days/weeks. Perhaps this will fix your issue...
Regards,
Tim

**Comment by sevensix** [comment]
Yes, please Update the Video.Js to the newest version, so we can use the responsive player. That would be great.

**Comment by lochmueller** [comment]
The update is part of the next release (and also the current Git master). I will close this issue...
